services:
  _defaults:
    autowire: true
    autoconfigure: true

  Tourze\JsonRPCEncryptBundle\EventSubscriber\:
    resource: '../../EventSubscriber/'
  Tourze\JsonRPCEncryptBundle\Service\:
    resource: '../../Service/'